name: Containers
on:
- push

jobs:
  containers:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.14.0
    steps:
    - name: Get node version
      run: |
        node -v
        cat /etc/os-release