name: Containers

on: push

jobs:
  containers:
    runs-on: ubuntu-latest
    container: 
      image: node:14-alpine3.14 
    steps:
    - name: Log the version
      run: |
        node -v
        cat /etc/os-release