name: Containers

on: push

jobs:
  containers:
    runs-on: ubuntu-latest
    container: 
      image: node:14-alpine3.14 
    steps:
    - name: Log the version
      run: |
        node -v
        cat /etc/os-release
jobs:
  multi-container:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
        - 3001:3000
      mongo:
        image: mongo
        ports:
        - 27017:27017
    steps:
    - name: Post a user
      run: "curl -X POST http://localhost:3001/pi/user -H 'Content-Type: application/json' -d '{\"username\": \"hello\", \"address\": \"dwerefd\"}'"
    - name: Get user
      run: "curl http://localhost:3001/api/user"