name: Containers
on:
- push

jobs:
  containers:
    runs-on: ubuntu-latest
    container:
      image: node:14-alpine
    steps:
    - name: Get node version
      run: |
        node -v
        cat /etc/os-release
  multi-container:
    runs-on: ubuntu-latest
    services:
      app: 
        image: alialaa17/node-api
        ports:
        - 3001:3000
      mongo:
        image: mongo
        ports:
        - 27017:27017
    steps:
    - name: Insert Data
      run: |
        curl -X POST http://localhost:3001/api/user =H ''Content-Type: pplication/json'' -d ''{"username": "sid", "address":"wertr"}'''
    - name: Read the data
      run: |
        curl -X GET http://localhost:3001/api/users

