name: Functions
on: push

jobs:
  functions:
    runs-on: ubuntu-latest
    steps:
    - name: Explore functions
      run: |
          echo ${{ contains('Hello','ll') }}
          echo ${{ startsWith('Elephant', 'El') }}
          echo ${{ endsWith('Integer','er') }}
          echo ${{ format('Hello {0} {1} {2}', 'World','!','!') }}