name: Matrix
on:
- push

jobs:
  matrix:
    runs-on: ubuntu-latest
    steps:
    - name: Get Node Version
      run: |
        node -v
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 6
    - name: Get the post Node version
      run: |
        node -v