name: Matrix
on:
- push

jobs:
  matrix:
    strategy:
      matrix:
        os: 
        - ubuntu-latest
        - macos-latest
        - windows-latest
        node-version:
        - 6
        - 8
        - 10
    runs-on: ${{ matrix.os }}
    steps:
    - name: Get Node Version
      run: |
        node -v
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Get the post Node version
      run: |
        node -v