name: Matix and Strategies

on: push

jobs:
  matrix-jobs:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [6,8,10]
      max-parallel: 2
    steps:
    - name: Log Node Version
      run: |
        node -v
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Log Node Version
      run: |
        node -v