name: Matrix
on:
- push

jobs:
  matrix:
    strategy:
      matrix:
        os: 
        - ubuntu-latest
        - macos-latest
        - windows-latest
        node-version:
        - 6
        - 8
        - 10
        include: 
        - os: ubuntu-latest
          node-version: 6
          is_ubuntu_6: true
        exclude:
        - os: macos-latest
        - node-version: 10
    runs-on: ${{ matrix.os }}
    steps:
    - name: Get Node Version
      run: |
        node -v
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Get the post Node version
      env:
          IS_UBUNTU_6: ${{ matrix.is_ubuntu_6 }}
      run: |
        node -v
        echo IS_UBUNTU_6: $IS_UBUNTU_6
