name: Matix and Strategies

on: pull_request

jobs:
  matrix-jobs:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [6,8,10]
        include:
        - os: ubuntu-latest
          node-version: 8
          is_ubuntu_8: "true"
        exclude:
        - os: ubuntu-latest
          node-version: 6
        - os: macos-latest
          node-version: 8
      max-parallel: 2
    env: 
      IS_UBUNTU_8: ${{ matrix.is_ubuntu_8}}
    steps:
    - name: Log Node Version
      run: |
        node -v
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Log Node Version
      run: |
        node -v
        echo "IS_UBUNTU_8 : ${IS_UBUNTU_8}"