name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs_on: ubuntu:latest
    steps:
    - name: Echo a String
      run: echo "Hello World"
    - name: Multiline script
      run: |
        node -v
        npm -v